##### GENERAL SETTINGS #####

# Reload tmux.conf with prefix + r
unbind r
bind r source-file ~/.tmux.conf \; display-message "Reloaded tmux.conf"

# Terminal & truecolor support
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"

# Better prefix
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Enable mouse mode
set -g mouse on

# Vim-style keys in copy mode
setw -g mode-keys vi

# Pane navigation with Vim keys
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Place status bar at top
set -g status-position bottom
# set -g status-style bg=default

##### PLUGINS #####
# TPM plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

##### STATUS BAR #####
# Let Catppuccin handle most styling
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

##### TPM INIT (must be last) #####
run '~/.tmux/plugins/tpm/tpm'
